feat: add support for tests and monorepo branches

diff --git a/.github/workflows/check-branch.yml b/.github/workflows/check-branch.yml
--- a/.github/workflows/check-branch.yml
+++ b/.github/workflows/check-branch.yml
@@ -23,9 +23,9 @@ jobs:
     if: needs.check-changesets.outputs.status == 'success' || needs.check-changesets.outputs.status == 'skipped'
     steps:
       - name: Throw error if wrong branch
-        if: github.base_ref == 'main' && github.head_ref != 'pre-release'
+        if: github.base_ref == 'main' && github.head_ref != 'pre-release' && (startsWith(github.head_ref,'tests/') || startsWith(github.head_ref,'monorepo/'))
         run: |
-          echo "ERROR: You can only merge to main from pre-release."
+          echo "ERROR: You can only merge to main from pre-release or from a branch starting with `tests/` or `monorepo/`."
           exit 1
       - uses: actions/checkout@v4
       - name: Setup Node.js 20
@@ -34,6 +34,10 @@ jobs:
           node-version: "20.x"
           cache: npm
       - run: npm ci
+      - name: Ensure if merging directly into main from a non-pre-release branch it has no changesets
+        if: github.base_ref == 'main' && github.head_ref != 'pre-release' && (startsWith(github.head_ref,'tests/') || startsWith(github.head_ref,'monorepo/'))
+        run: |
+          if npx changeset status | grep "Packages to be bumped"; then echo "Found changesets. Changesets are not allowed on direct merges, you must merge into pre-release first." && exit 1; else exit 0; fi
       - name: Ensure pre-release branch is in pre-release mode
         if: github.base_ref == 'pre-release' && (startsWith(github.head_ref,'release/') != true)
         run: |
